

services:
  web:
    build: .
    container_name: fidden_web
    working_dir: /app
    command: >
      uvicorn fidden.asgi:application
      --host 0.0.0.0
      --port 8090
      --ws websockets
    volumes:
      - ./media:/app/media
      - staticfiles:/app/staticfiles
      # - ./:/app  <-- Commented out for production to use built image code
    ports:
      - "8090:8090"
    environment:
      - DJANGO_SETTINGS_MODULE=fidden.settings
      - DATABASE_URL
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - S3_REGION
      - STRIPE_SECRET_KEY
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_WEBHOOK_SECRET
      - PAYPAL_MODE
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - PAYPAL_WEBHOOK_ID
      - GOOGLE_APPLICATION_CREDENTIALS
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8090/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    container_name: fidden_celery
    working_dir: /app
    command: sh -c "celery -A fidden worker --loglevel=info"
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=fidden.settings
      - DATABASE_URL
      - SECRET_KEY
      - DEBUG
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_REGION_NAME
      - S3_REGION
      - STRIPE_SECRET_KEY
      - PAYPAL_MODE
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - GOOGLE_APPLICATION_CREDENTIALS
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "celery -A fidden status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery-beat:
    build: .
    container_name: fidden_celery_beat
    working_dir: /app
    command:  sh -c "until python manage.py migrate; do echo Waiting for DB; sleep 3; done; celery -A fidden beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=fidden.settings
      - DATABASE_URL
      - SECRET_KEY
      - DEBUG
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[c]elery beat' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8
    container_name: fidden_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media:
  staticfiles: